//
//  vouch_ios_sdk-Swift.h
//  vouch-ios-sdk
//
//  Swift to Objective-C interface header
//  This file documents the Objective-C API exposed by VouchSDKBridge.swift
//  Note: The actual header is auto-generated by Xcode during compilation
//

#ifndef VOUCH_IOS_SDK_SWIFT_H
#define VOUCH_IOS_SDK_SWIFT_H

#import <Foundation/Foundation.h>

#if defined(__cplusplus)
#define VOUCH_EXTERN extern "C"
#else
#define VOUCH_EXTERN extern
#endif

NS_ASSUME_NONNULL_BEGIN

// MARK: - VouchErrorReasonObjC

typedef NS_ENUM(NSInteger, VouchErrorReasonObjC) {
    VouchErrorReasonObjCDataSourceOrCustomerNotFound = 0,
    VouchErrorReasonObjCOutdatedVersion = 1,
    VouchErrorReasonObjCCreatingProofRequestFailed = 2,
    VouchErrorReasonObjCBackgroundTimeout = 3,
    VouchErrorReasonObjCRequestTooLarge = 4,
    VouchErrorReasonObjCDataSourceMisconfigured = 5,
    VouchErrorReasonObjCProvingFailed = 6,
    VouchErrorReasonObjCProofUploadFailed = 7,
    VouchErrorReasonObjCAttachmentReuploadFailed = 8,
    VouchErrorReasonObjCProofIdTaken = 9,
    VouchErrorReasonObjCNetworkConnectionLost = 10
};

// MARK: - VouchSuccessObjC

@interface VouchSuccessObjC : NSObject

@property (nonatomic, readonly, copy) NSString *proofId;

- (instancetype)initWithProofId:(NSString *)proofId;

@end

// MARK: - VouchErrorObjC

@interface VouchErrorObjC : NSError

@property (nonatomic, readonly, copy) NSString *proofId;
@property (nonatomic, readonly) VouchErrorReasonObjC reason;

- (instancetype)initWithProofId:(NSString *)proofId reason:(VouchErrorReasonObjC)reason;

@end

// MARK: - VouchSDKBridge

typedef void (^VouchSDKBridgeCompletionHandler)(VouchSuccessObjC * _Nullable success, VouchErrorObjC * _Nullable error);

@interface VouchSDKBridge : NSObject

@property (nonatomic, readonly, copy) NSString *customerId;

/**
 * Initialize the Vouch SDK bridge with a customer ID
 *
 * @param customerId The unique customer identifier
 * @return An initialized VouchSDKBridge instance
 */
- (instancetype)initWithCustomerId:(NSString *)customerId;

/**
 * Start a proof request flow
 *
 * This method will present the Vouch SDK UI modally on the current view controller.
 * The completion handler will be called when the proof flow completes or fails.
 *
 * @param dataSourceId The data source identifier
 * @param webhookUrl The webhook URL for callbacks
 * @param inputs Additional input parameters (optional, can be nil)
 * @param completion Completion handler called with success or error
 */
- (void)startWithDataSourceId:(NSString *)dataSourceId
                    webhookUrl:(NSString *)webhookUrl
                        inputs:(NSDictionary<NSString *, NSString *> * _Nullable)inputs
                    completion:(VouchSDKBridgeCompletionHandler)completion;

/**
 * Dismiss the currently presented SDK view
 *
 * @param completion Optional completion handler called after dismissal
 */
- (void)dismissWithCompletion:(void (^ _Nullable)(void))completion;

/**
 * Get the SDK version
 *
 * @return The version string
 */
+ (NSString *)sdkVersion;

@end

NS_ASSUME_NONNULL_END

#endif /* VOUCH_IOS_SDK_SWIFT_H */
